### ISSUE TITLE
timezone_iii 1.1.6 archive lacked magic header!

### ISSUE THREAD

**Issue by electriquo** [Stromweld/timezone_iii#17]
berks is having a problem downloading the cookbook due to [lack of magic header (in tar)][1].
this is what berks outputs when running `berks install` or `berks update`

```bash
ArgumentError "\x80\x00\x00\x00\x02\xDB\xFD\x17" is not an octal string
```
this affects version 1.1.6, 1.1.5 1.1.4, 1.1.3 and i didn't check the rest (note that the error above is for 1.1.6)

seems that there is no way to bypass it using berks.
could someone please point out what is the issue.

[1]: https://github.com/berkshelf/berkshelf/issues/1744#issuecomment-373778578

**Comment by Stromweld** [comment]
so that seems to be a bug in the ruby gems stuff according to the link you found. The quickest fix for now that seems to work is to run `gem update --system 2.7.5` as 2.7.6 has the bug. You may have to run `chef gem update --system 2.7.5` depending on your environment. Chef is working on having a fix in the next chefdk release.
